name: Pull Request and Push Action

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review, review_requested, review_request_removed]
  push:
    branches: [ main ]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  call-test-lint:
    uses: ./.github/workflows/test-lint.yml
    permissions:
      contents: read
    with:
      ref: ${{ github.event.pull_request.head.sha || github.sha }}
